### ISSUE TITLE
there is no super key on a phone

### ISSUE THREAD

**Issue by Cyborgscode** [chiken88/gnome-dpi-switcher#1]
Hi, 

activating this via a keyshortcut only works with a keyboard, which Pinephones or Libre M5s do not have. 

Pls create an app icon for the gnome-status bar and enable auto dpi changes depending on which app is front-most.
A configurator to add new dpi scales associated with apps. 

It does not make sense for you, but if you have seen this:

https://github.com/Cyborgscode/pinephone/tree/main/windowmaximizer

which adapts windows on the fly and this scaling problem with firefox and chrome :

https://marius.bloggt-in-braunschweig.de/files/2020/12/Bildschirmfoto-vom-2020-12-01-16-15-11-300x150.png

this issue report will make much more sense  to you :D

**Comment by aivanovski** [comment]
Closed as this project is abandoned. I left the Gnome several years ago and will never come back again.
